### ISSUE TITLE
Cannot copy values

### ISSUE THREAD

**Issue by leoheck** [mattvilim/gtkwave#1]
Hello, I am simulating and analyzing a processor with GtkWave which is a great tool by the way. 

My issue is that I need to copy values from there but could not find a way to do this.

Is this possible? How can I do this?

For instance, this one:
![IMG-20210520-WA0009](https://user-images.githubusercontent.com/1277920/119016408-4892fb80-b970-11eb-8189-c1cfa0cbf0ff.jpg)

Does GtkWave has any way to do that?

I am using `GTKWave Analyzer v3.3.86 (w)1999-2017 BSI` by the way.

**Comment by mcruaro** [comment]
1. In View tab, select "Show Mouseover"
2. In View tab, select "Mouse copies to clipboard"
3. Click over your signal
4. Ctrl+C (it will copy the signal value)
5. Paste where you want
